# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KendallNeighbour <- function(rank) {
    .Call('rankdistext_KendallNeighbour', PACKAGE = 'rankdistext', rank)
}

CayleyNeighbour <- function(rank) {
    .Call('rankdistext_CayleyNeighbour', PACKAGE = 'rankdistext', rank)
}

LogC <- function(fai) {
    .Call('rankdistext_LogC', PACKAGE = 'rankdistext', fai)
}

CWeightGivenPi <- function(r1, r2) {
    .Call('rankdistext_CWeightGivenPi', PACKAGE = 'rankdistext', r1, r2)
}

FindV <- function(obs, pi0) {
    .Call('rankdistext_FindV', PACKAGE = 'rankdistext', obs, pi0)
}

LogC_Component <- function(fai) {
    .Call('rankdistext_LogC_Component', PACKAGE = 'rankdistext', fai)
}

cycle_decomp <- function(comp) {
    .Call('rankdistext_cycle_decomp', PACKAGE = 'rankdistext', comp)
}

FindCayley <- function(obs, pi0) {
    .Call('rankdistext_FindCayley', PACKAGE = 'rankdistext', obs, pi0)
}

Wtau <- function(obs, pi0) {
    .Call('rankdistext_Wtau', PACKAGE = 'rankdistext', obs, pi0)
}

AllPerms <- function(nobj) {
    .Call('rankdistext_AllPerms', PACKAGE = 'rankdistext', nobj)
}

